config/routes.rb
Rails.application.routes.draw do
  resources :artists
  
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
        @artists = Artist.all
    end

    def show
        @artist = Artist.find(params[:id])
        @album = @artist.albums
    end

    def new
        @artist = Artist.new
    end

    def create
        @nuevo = Artist.new(artist_params)

        if @nuevo.save
            redirect_to artists_path
        else
            render new
            
        end
    end

    private

    def artist_params
        params.require(:artist).permit(:name, :image_url)        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-10 d-flex flex-row flex-wrap justify-content-around">
            <% @artists.each do |artist| %>
                <div >
                    <div class="card">
                        <img src = <%= artist.image_url %>>
                        <div class="card-body">
                            <h5 class="card-title"><%= artist.name %></h5>
                            <%= link_to "Ver más", artist, class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
             <% end %>
        </div>
        <div class="col-sm-2">
            <%= link_to "New Artist", new_artist_path, class: "btn btn-dark"%>
        </div>
        
        
    </div>


</div>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= form_with(model: @artist) do |f| %>

    <div>
        <%= f.label :nombre %>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :imagen%>
        <%= f.text_field :image_url%>
    </div>
    <div>
        <%= f.submit "Guardar"%>
    </div>


<%end%>

app/views/artists/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-9">
            <div class="row d-flex flex-column">
                <h1><%= @artist.name %></h1>      
                <h4> Albums (<%= @album.length %>) </h4>
            </div>
            <div class="row">
                <% @album.each do |item|%> 
                <div class="col-sm-3">
                    <div class="card albumsShow">
                        <img src="<%= item.image_url %>" class="card-img-top">
                        <div class="card-body d-flex align-items-start">
                            <h5><%= item.name %></h5>
                            <h5><%= item.released_at %></h5>
                        </div>
                      </div>
                </div>         
            <% end %>
            </div>
        </div>
        <div class="col-sm-3">
            <img src="<%= @artist.image_url %>" class="artist-show">
        </div>    
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">Real Music</span>
    
    <div class="collapse navbar-collapse" style="width: 100%;" >
        <ul class="navbar-nav " style="width: 100%;" >
            <div class = "d-flex flex-row d-flex justify-content-between" style="width: 100%;">
                <div class = "d-flex flex-row">
                    <li class="nav-item">
                        <%= link_to "Artistas", artists_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Mi música</a>
                    </li>
                </div>
                <div>
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Mi Cuenta
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
        </ul>
    </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>